import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import SessionWrapper from "@/components/Sessionwrapper";
import { connectToMongoDB } from "@/lib/db";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Computer Store",
  description: "Generated by create next app",
};

export default function PageLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  connectToMongoDB();
  return (
    <SessionWrapper>
      <html lang="en">
        <head>
          <meta charSet="UTF-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet"></link>
        </head>
        <body className={inter.className}>
          {children}
          <Script strategy="lazyOnload" id="scroll-script">
            {
            `
              const body = document.body;
              let lastScroll = 0;
              window.addEventListener('scroll', () => {
                const currentScroll = window.pageYOffset;

                if(currentScroll<=0){
                  body.classList.remove("scroll-up")
                }

                if(currentScroll > lastScroll && !body.classList.contains("scroll-down")){
                  body.classList.remove("scroll-up");
                  body.classList.add("scroll-down");
                }

                if(currentScroll < lastScroll && body.classList.contains("scroll-down")){
                  body.classList.remove("scroll-down");
                  body.classList.add("scroll-up");
                }

                lastScroll = currentScroll;
              });
            `
            }
          </Script>
        </body>
      </html>
    </SessionWrapper>
  );
}
