
import type { Metadata } from "next";
import Footer from "@/components/Footer";
import HeroPage from "./(HomePage)/HeroPage";


export const metadata: Metadata = {
  title: "Home-Store",
  description: "Generated by create next app",
};

export default function Homepage() {
  return (
    <>
      <HeroPage />
      <Footer />
    </>
  )
}
