import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Company-Store",
  description: "Generated by create next app",
};

export default function CompanyPage() {
    return (
        <div className='py-10 text-white'>
            Company Page
        </div>
    );
}
