import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Testing-Store",
  description: "Generated by create next app",
};

export default function TestPage() {
  return (
    <div className='py-10 text-white'>
      Testing
    </div>
  )
}

