import Navbar from "@/UIdashboard/dashboard/navbar/navbar";
import Sidebar from "@/UIdashboard/dashboard/sidebar/sidebar";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Dashbord Store",
    description: "Generated by create next app",
  };
export default function Layout({
    children,
  }: Readonly<{
    children: React.ReactNode;
}>) {
  return (
    <div className='max-w-full mx-auto flex text-white'>
        <div className="bg-slate-800 p-5 w-[250px]">
            <Sidebar />
        </div>
        <div className="bg-slate-900 flex-1 p-5 min-h-screen">
            <Navbar />
            {children}
        </div>
    </div>
  )
}
