import type { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "About-Store",
  description: "Generated by create next app",
};

export default function AboutPage() {
  return (
    <div className="bg-gray-100 min-h-screen">
      <header className="bg-blue-600 text-white py-6">
        <div className="container mx-auto px-6">
          <h1 className="text-3xl font-bold">About Us</h1>
        </div>
      </header>
      <main className="container mx-auto px-6 py-12">
        <section className="mb-12">
          <h2 className="text-2xl font-bold mb-4">Our Company</h2>
          <p className="text-gray-700 leading-relaxed">
            Welcome to [Your Company Name], where we are dedicated to providing exceptional services and
            products to our valued clients. Our mission is to deliver high-quality solutions that meet the
            unique needs of each customer. With a team of experienced professionals, we strive to exceed
            expectations and drive success for your business.
          </p>
        </section>
        <section>
          <h2 className="text-2xl font-bold mb-4">Meet Our Team</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            <div className="bg-white shadow-md rounded-lg p-6 transform transition-transform duration-300 hover:scale-105">
                {/* <Image
                    className="w-32 h-32 mx-auto rounded-full mb-4"
                    src="/path-to-image.jpg"
                    alt="Team Member"
                /> */}
                <h3 className="text-xl font-bold mb-2">John Doe</h3>
                <p className="text-gray-600 mb-2">CEO</p>
                <p className="text-gray-700 leading-relaxed">
                    John is the visionary behind our company, with over 20 years of experience in the
                    industry.
                </p>
            </div>
            <div className="bg-white shadow-md rounded-lg p-6 transform transition-transform duration-300 hover:scale-105">
                {/* <Image
                    className="w-32 h-32 mx-auto rounded-full mb-4"
                    src="/path-to-image.jpg"
                    alt="Team Member"
                /> */}
                <h3 className="text-xl font-bold mb-2">Jane Smith</h3>
                <p className="text-gray-600 mb-2">COO</p>
                <p className="text-gray-700 leading-relaxed">
                    Jane oversees our operations and ensures everything runs smoothly. She has a keen eye for
                    detail.
                </p>
            </div>
            <div className="bg-white shadow-md rounded-lg p-6 transform transition-transform duration-500 hover:scale-105">
                {/* <Image
                    className="w-32 h-32 mx-auto rounded-full mb-4"
                    src="/path-to-image.jpg"
                    alt="Team Member"
                /> */}
                <h3 className="text-xl font-bold mb-2">Emily Johnson</h3>
                <p className="text-gray-600 mb-2">CTO</p>
                <p className="text-gray-700 leading-relaxed">
                    Emily is our tech guru, leading the development of innovative solutions to drive our
                    business forward.
                </p>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}

